//change the output names.

export const Dataproducts = [
  {
    id: 1,
    title: "art-monkey",
    price: "$5.1",
    category: "art",
    image: "/images/art/fox.jpeg",
  },
  {
    id: 2,
    title: "arts-monkey",
    price: "$5.2",
    category: "art",
    image: "/images/art/etsy.jpeg",
  },
  {
    id: 3,
    title: "arts-monkey",
    price: "$5.3",
    category: "art",
    image: "/images/art/dudde.png",
  },
  {
    id: 4,
    title: "art-monkey",
    price: "$5.4",
    category: "art",
    image: "/images/art/girl.png",
  },
  {
    id: 5,
    title: "arts-monkey",
    price: "$5.5",
    category: "art",
    image: "/images/art/skeleton.jpeg",
  },
  {
    id: 6,
    title: "arts-monkey",
    price: "$5.6",
    category: "art",
    image: "/images/art/skull.jpeg",
  },
  {
    id: 7,
    title: "art-monkey",
    price: "$5.7",
    category: "art",
    image: "/images/art/women.jpeg",
  },
  {
    id: 8,
    title: "arts-monkey",
    price: "$5.8",
    category: "art",
    image: "/images/games/g1.png",
  },
  {
    id: 9,
    title: "arts-monkey",
    price: "$5.9",
    category: "art",
    image: "/images/games/g2.png",
  },
  {
    id: 10,
    title: "art-monkey",
    price: "$5.10",
    category: "art",
    image: "/images/games/g3.jpeg",
  },
  {
    id: 11,
    title: "arts-monkey",
    price: "$5.11",
    category: "art",
    image: "/images/games/g5.jpeg",
  },
  // {
  //   id: 12,
  //   title: "arts-monkey",
  //   price: "$5.12",
  //   category: "art",
  //   image: "s/images/art/fox.jpeg",
  // },
  // {
  //   id: 13,
  //   title: "art-monkey",
  //   price: "$5.13",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 14,
  //   title: "arts-monkey",
  //   price: "$5.14",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 15,
  //   title: "arts-monkey",
  //   price: "$5.15",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 16,
  //   title: "art-monkey",
  //   price: "$5.16",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 17,
  //   title: "art-monkey",
  //   price: "$5.17",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 18,
  //   title: "arts-monkey",
  //   price: "$5.18",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 19,
  //   title: "arts-monkey",
  //   price: "$5.19",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
  // {
  //   id: 20,
  //   title: "art-monkey",
  //   price: "$5.20",
  //   category: "art",
  //   image: "/images/art/fox.jpeg",
  // },
];
